version: '3'
services:

  # TODO two networks, one backend and one frontend

  # TODOs
  # - wait for postgres to become available
  # - python manage.py migrate
  # - python manage.py loaddata fixtures/initial_data.json
  # - python manage.py collectstatic

  frontend:
    build: ./frontend
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    volumes:
      - django-staticfiles:/usr/share/nginx/html/static
    depends_on:
      - backend

  backend:
    build: ./backend
    env_file:
      - .env
    volumes:
      - django-staticfiles:/app/static
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    env_file:
      - .env

  # redis:
  #   image: redis

volumes:
  django-staticfiles: