version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - 8000:80
    volumes:
      - wato-staticfiles:/usr/share/nginx/html/static

  backend:
    build: ./backend
    volumes:
      - wato-staticfiles:/app/static
    env_file:
      - .env.local

  postgres:
    image: postgres
    volumes:
      - wato-db-data:/var/lib/postgresql/data
    env_file:
      - .env.local

volumes:
  wato-staticfiles:
  wato-db-data:
